### PR TITLE
[Rebased] Support for custom HTTP headers

### PR DESCRIPTION
**Pull request by bpolaszek**
Hello @clue, 

This one is a rebased version of #10. When you've got some little time, could you please review this?
If you merge, please co-author @qharnay since he did the biggest part of the job :-) 

Do you plan to tag a 0.1? I'll soon require that dependency on a production app (server listening to a Mercure server, with authentication) and even if not considered stable, at least avoid relying `dev-master` in case of breaking changes.

Thank you much!
Ben

### CODE REVIEW

**Comment by Xusifob** [comment]
Any info on the merge of this PR ? 

+1 for adding a 0.1 tag to the project !

**Comment by bpolaszek** [comment]
Ping @clue 🙂

**Comment by bpolaszek** [comment]
Time to ping again - @clue could you please review?

**Comment by clue** [comment]
@bpolaszek Thanks for looking into this and the friendly reminder! I'm currently in the process of applying some major upgrades to @ReactPHP that will also affect this project here. Once this done, I'll make sure take a look at this again as soon as time permits :+1:

**Comment by bpolaszek** [comment]
@clue No worries 🙂 I assume you're kinda busy with X-Framework 🍿 

No emergency on my side, I'll ping you again in a few months when I'll cleanup my forks 😄

**Comment by SimonFrings** [comment]
@bpolaszek I continued the conversation in #10 :+1:

**Comment by clue** [comment]
I've just filed https://github.com/reactphp/http/issues/449 as a way to keep track of this ticket upstream and believe this is the best way to address this :+1:

In the meantime, I'll assume this one is resolved and will close this for now, please feel free to report back otherwise :+1:

**Pull request closed without merging**
